language: generic

## Force usage of "Ubuntu Xenial" as on older versions
## program "realpath" is not working for some reason.
os: linux
dist: xenial
services: docker
sudo: required

## Build environment is used as submodule so let
## submodules will be checked out too.
git:
  submodules: true

## Split per-architecture builds into separate jobs.
env:
  matrix:
    - TERMUX_ARCH=aarch64
    - TERMUX_ARCH=arm
    - TERMUX_ARCH=i686
    - TERMUX_ARCH=x86_64

## Copy our packages to the build environment.
before_script:
  - cp -a ./packages/* ./termux-packages/packages/
  - cp ./scripts/setup-build-environment.sh ./termux-packages/

## Execute build-dispatching script.
script:
  - unset BINTRAY_USERNAME
  - unset BINTRAY_API_KEY
  - MODIFIED_PACKAGES=$(./scripts/get-modified-packages.sh)
  - cd ./termux-packages
  - |
    for package in $MODIFIED_PACKAGES; do
        ./scripts/run-docker.sh ./build-package.sh -q -a "$TERMUX_ARCH" "$package" || exit 1
    done
